---
  ipv4_address:
    host_10.1.0.252:
      ipv4_desc:
      range: absent 
      ipv4_mask: 10.1.0.252/32
    host_10.1.0.253:
      ipv4_desc:
      range: absent 
      ipv4_mask: 10.1.0.253/32
    host_10.2.0.65:
      ipv4_desc:
      range: absent 
      ipv4_mask: 10.2.0.65/32   
    host_10.16.0.252:
      ipv4_desc:
      range: absent 
      ipv4_mask: 10.16.0.252/32 
    host_10.5.0.11:
      ipv4_desc:
      range: absent 
      ipv4_mask: 10.5.0.11/32
    host_192.168.0.245:
      ipv4_desc:
      range: absent 
      ipv4_mask: 192.168.0.245/32
  ipv4_add_grp:
    ipv4_add-1: 'host_10.1.0.252'
    ipv4_add-2: 'host_10.1.0.253'
    ipv4_add-3: 'host_10.2.0.65'
    ipv4_add-4: 'host_10.16.0.252'
    ipv4_add-5: 'host_10.5.0.11'
    ipv4_add-6: 'host_192.168.0.245:'
    


